# Defaults
alias qr='zbarimg'

# Remotes
alias server='xfreerdp3 /v:23.112.119.118 /u:emby /p:Will0w\$rul3s'

# VPNs
alias vpn-norway='sudo openvpn --config /etc/openvpn/client/Norway.conf'
alias vpn-czech='sudo openvpn --config /etc/openvpn/client/Czech_Republic.conf'
